name: Inspect Firmware Binaries

on:
  push:
    paths:
      - '**.bin'
      - '.github/workflows/**'

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repo files
        run: ls -la

      - name: Hexdump binaries (First 20 lines)
        run: |
          hexdump -C CassiesArcade.ino.bootloader.bin | head -n 20 > bootloader_dump.txt
          hexdump -C CassiesArcade.ino.bin | head -n 20 > firmware_dump.txt
          hexdump -C CassiesArcade.ino.partitions.bin | head -n 20 > partitions_dump.txt

      - name: Upload hexdump inspection files
        uses: actions/upload-artifact@v4
        with:
          name: firmware-inspection
          path: |
            bootloader_dump.txt
            firmware_dump.txt
            partitions_dump.txt

      - name: Upload full binaries
        uses: actions/upload-artifact@v4
        with:
          name: firmware-binaries
          path: |
            CassiesArcade.ino.bootloader.bin
            CassiesArcade.ino.bin
            CassiesArcade.ino.partitions.bin
